// Command genstrengthwords regenerates internal/crypto/strength_words.go from
// rank-ordered public wordlists. Kawarimi's user base is Spanish- and
// English-speaking, so both vocabularies get equal weight.
//
// Inputs (download next to this file before running):
//
//	curl -LO https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Common-Credentials/10k-most-common.txt
//	curl -LO https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english.txt
//	curl -LO https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/es/es_50k.txt
//
// Usage: go run ./tools/genstrengthwords (from the repo root, with the three
// files in the current directory); it writes internal/crypto/strength_words.go.
package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"unicode"
	"unicode/utf8"
)

func deaccent(s string) string {
	repl := strings.NewReplacer("á", "a", "é", "e", "í", "i", "ó", "o", "ú", "u", "ü", "u", "ñ", "n")
	return repl.Replace(s)
}

func clean(word string, minLen int) (string, bool) {
	word = strings.ToLower(strings.TrimSpace(word))
	if !utf8.ValidString(word) || len([]rune(word)) < minLen || len(word) > 30 {
		return "", false
	}
	for _, r := range word {
		if unicode.IsSpace(r) || r == '"' || r == '\\' || !unicode.IsPrint(r) {
			return "", false
		}
	}
	return word, true
}

// readList reads one rank-ordered wordlist: lowercased, length-filtered,
// deaccented, deduplicated (first occurrence keeps the best rank).
func readList(path string, minLen int, takeFirstField bool, limit int) []string {
	f, err := os.Open(path)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	seen := map[string]bool{}
	var out []string
	sc := bufio.NewScanner(f)
	for sc.Scan() && (limit == 0 || len(out) < limit) {
		line := sc.Text()
		if takeFirstField {
			line = strings.Fields(line + " x")[0]
		}
		w, ok := clean(line, minLen)
		if !ok {
			continue
		}
		w = deaccent(w)
		if seen[w] {
			continue
		}
		seen[w] = true
		out = append(out, w)
	}
	return out
}

func emit(b *strings.Builder, name, comment string, words []string) {
	fmt.Fprintf(b, "// %s\n", comment)
	fmt.Fprintf(b, "var %s = []string{\n", name)
	for i := 0; i < len(words); i += 8 {
		end := i + 8
		if end > len(words) {
			end = len(words)
		}
		b.WriteString("\t")
		for _, w := range words[i:end] {
			fmt.Fprintf(b, "%q, ", w)
		}
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
}

func main() {
	passwords := readList("10k-most-common.txt", 3, false, 0)
	english := readList("google-10000-english.txt", 3, false, 0)
	spanish := readList("es_50k.txt", 3, true, 10000)

	var b strings.Builder
	b.WriteString("// Code generated by go run ./tools/genstrengthwords. DO NOT EDIT.\n")
	b.WriteString("//\n// Rank order = source frequency order. Sources:\n")
	b.WriteString("//   strengthCommonPasswords: SecLists Common-Credentials/10k-most-common.txt\n")
	b.WriteString("//   strengthEnglishWords:    first20hours/google-10000-english (len >= 3)\n")
	b.WriteString("//   strengthSpanishWords:    hermitdave/FrequencyWords es_50k top 10000 (len >= 3, deaccented)\n")
	b.WriteString("\npackage crypto\n\n")
	emit(&b, "strengthCommonPasswords", "strengthCommonPasswords is rank-ordered: index+1 is the password's popularity rank.", passwords)
	emit(&b, "strengthEnglishWords", "strengthEnglishWords is frequency-ordered English vocabulary for pattern matching.", english)
	emit(&b, "strengthSpanishWords", "strengthSpanishWords is frequency-ordered Spanish vocabulary (deaccented).", spanish)

	if err := os.WriteFile("internal/crypto/strength_words.go", []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("passwords=%d english=%d spanish=%d\n", len(passwords), len(english), len(spanish))
}
